### Create Product Item
POST localhost:8081/api/v1/products
Content-Type: application/json

{
  "title": "iPhone 67 max",
  "description": "A brand new iPhone",
  "forWhatCountry": "USA",
  "price": 1500
}

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}

### Get Product Item
GET localhost:8081/api/v1/products/1

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}

### Update Product Item
PUT localhost:8081/api/v1/products/2
Content-Type: application/json

{
  "title": "A new title hbjlbeljben"
}

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}

### Delete Product Item
DELETE localhost:8081/api/v1/products/3
Content-Type: application/json

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}
