### Create Product Item
POST localhost:8081/api/v1/products
Content-Type: application/json

{
  "title": "iPhone 15",
  "description": "A new iPhone",
  "forWhatCountry": "Japan",
  "price": 799
}

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}

### Get Product Item
GET localhost:8081/api/v1/products/1

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}

### Update Product Item
PUT localhost:8081/api/v1/products/1
Content-Type: application/json

{
  "description": "Btw this is a brand new IPHONE BABY"
}

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}

### Delete Product Item
DELETE localhost:8081/api/v1/products/1
Content-Type: application/json

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}